/** Metadados locais espelhando o catálogo do servidor (ícones e bordas no HUD). */
export const COSMETIC_BY_ID: Record<string, { id: string; nome: string; icon: string }> = {
  avatar_inicial: { id: 'avatar_inicial', nome: 'Inicial', icon: 'letter' },
  avatar_portal: { id: 'avatar_portal', nome: 'Portal', icon: 'star' },
  avatar_chama: { id: 'avatar_chama', nome: 'Chama', icon: 'flame' },
  avatar_estrela: { id: 'avatar_estrela', nome: 'Estrela', icon: 'star' },
  avatar_trofeu: { id: 'avatar_trofeu', nome: 'Troféu', icon: 'trophy' },
  avatar_haltere: { id: 'avatar_haltere', nome: 'Haltere', icon: 'dumbbell' },
  avatar_coracao: { id: 'avatar_coracao', nome: 'Coração', icon: 'heart' },
  avatar_coroa: { id: 'avatar_coroa', nome: 'Coroa', icon: 'crown' },
  avatar_foguete: { id: 'avatar_foguete', nome: 'Foguete', icon: 'rocket' },
  avatar_escudo: { id: 'avatar_escudo', nome: 'Escudo', icon: 'shield' },
  borda_basica: { id: 'borda_basica', nome: 'Básica', icon: 'shield' },
  borda_bronze: { id: 'borda_bronze', nome: 'Bronze', icon: 'medal' },
  borda_prata: { id: 'borda_prata', nome: 'Prata', icon: 'star' },
  borda_ouro: { id: 'borda_ouro', nome: 'Ouro', icon: 'crown' },
  borda_esmeralda: { id: 'borda_esmeralda', nome: 'Esmeralda', icon: 'gem' },
  borda_ametista: { id: 'borda_ametista', nome: 'Ametista', icon: 'moon' },
  borda_fogo: { id: 'borda_fogo', nome: 'Fogo', icon: 'flame' },
  borda_lendario: { id: 'borda_lendario', nome: 'Lendária', icon: 'gem' },
  borda_imparavel: { id: 'borda_imparavel', nome: 'Imparável', icon: 'shield' },
  titulo_eu_sou_heroi: { id: 'titulo_eu_sou_heroi', nome: 'Eu sou herói', icon: 'crown' },
  titulo_guerreiro: { id: 'titulo_guerreiro', nome: 'Guerreiro do core', icon: 'shield' },
  titulo_imparavel: { id: 'titulo_imparavel', nome: 'Imparável', icon: 'flame' },
  titulo_lenda: { id: 'titulo_lenda', nome: 'Lenda viva', icon: 'gem' },
  titulo_dono_do_jogo: { id: 'titulo_dono_do_jogo', nome: 'Dono do Jogo', icon: 'crown' },
  fundo_padrao: { id: 'fundo_padrao', nome: 'Padrão', icon: 'star' },
  fundo_aurora: { id: 'fundo_aurora', nome: 'Aurora', icon: 'star' },
  fundo_vulcao: { id: 'fundo_vulcao', nome: 'Vulcão', icon: 'flame' },
  fundo_galaxia: { id: 'fundo_galaxia', nome: 'Galáxia', icon: 'moon' },
  som_classico: { id: 'som_classico', nome: 'Clássico', icon: 'zap' },
  som_suave: { id: 'som_suave', nome: 'Suave', icon: 'star' },
  som_chime: { id: 'som_chime', nome: 'Sino', icon: 'zap' },
  som_pop: { id: 'som_pop', nome: 'Pop', icon: 'star' },
  som_arcade: { id: 'som_arcade', nome: 'Arcade', icon: 'rocket' },
  som_retro: { id: 'som_retro', nome: 'Retro', icon: 'rocket' },
  som_pixel: { id: 'som_pixel', nome: 'Pixel', icon: 'star' },
  som_metal: { id: 'som_metal', nome: 'Metal', icon: 'shield' },
  som_epico: { id: 'som_epico', nome: 'Épico', icon: 'trophy' },
  efeito_padrao: { id: 'efeito_padrao', nome: 'Padrão', icon: 'medal' },
  efeito_confete: { id: 'efeito_confete', nome: 'Confete', icon: 'star' },
  efeito_raios: { id: 'efeito_raios', nome: 'Raios', icon: 'zap' },
  efeito_fogo: { id: 'efeito_fogo', nome: 'Chamas', icon: 'flame' },
  efeito_agua: { id: 'efeito_agua', nome: 'Onda Azul', icon: 'star' },
  efeito_glitch: { id: 'efeito_glitch', nome: 'Quebra de Tela', icon: 'zap' },
};
