import { withCustomParams, withLevelParams } from '../../utils/exercise-params.js';
import type { IExercise } from '../../types/index.js';

/** Exercícios gated por equipamento — `ativo: false` até o usuário marcar que possui o item. */
export const equipmentExercises: IExercise[] = [
  // —— Prancha 9 em 1 ——
  withCustomParams(
    {
      slug: 'push-up-board-chest',
      nome: 'Push-Up Board — Peito',
      nome_pt: 'Flexão na prancha — Peito (vermelho)',
      nivel: 2,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'A',
      modo: 'reps',
      descricao: 'Encaixe as pegadas nos slots vermelhos, na largura dos ombros apontando à frente. Cotovelos a ~45°, desça o peito até a altura dos cabos. Foco em peitoral com core firme.',
      media: { gif: 'push-up.gif' },
      ativo: false,
      equipamento: 'push_up_board',
    },
    { repeticoes_iniciante: 8, repeticoes_intermediario: 12, repeticoes_avancado: 16 },
  ),
  withCustomParams(
    {
      slug: 'push-up-board-triceps',
      nome: 'Push-Up Board — Tríceps',
      nome_pt: 'Flexão na prancha — Tríceps (verde)',
      nivel: 2,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'A',
      modo: 'reps',
      descricao: 'Encaixe as pegadas nos slots verdes, com pegada estreita (mãos próximas). Cotovelos colados ao corpo descendo para trás. Ênfase em tríceps e peito interno.',
      media: { gif: 'push-up.gif' },
      ativo: false,
      equipamento: 'push_up_board',
    },
    { repeticoes_iniciante: 6, repeticoes_intermediario: 10, repeticoes_avancado: 14 },
  ),
  withCustomParams(
    {
      slug: 'push-up-board-shoulders',
      nome: 'Push-Up Board — Ombros',
      nome_pt: 'Flexão na prancha — Ombros (azul)',
      nivel: 3,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'B',
      modo: 'reps',
      descricao: 'Encaixe as pegadas nos slots azuis, mãos largas e à frente. Incline o tronco para frente (quadril mais alto) para ativar deltoides e estabilizadores.',
      media: { gif: 'incline-push-up.gif' },
      ativo: false,
      equipamento: 'push_up_board',
    },
    { repeticoes_iniciante: 6, repeticoes_intermediario: 9, repeticoes_avancado: 12 },
  ),
  withCustomParams(
    {
      slug: 'push-up-board-back',
      nome: 'Push-Up Board — Costas',
      nome_pt: 'Flexão na prancha — Costas (amarelo)',
      nivel: 3,
      musculo_principal: 'superior',
      musculos_secundarios: ['core', 'obliquos'],
      tempo_recomendado: 30,
      prioridade: 'B',
      modo: 'reps',
      descricao: 'Encaixe as pegadas nos slots amarelos, mãos anguladas e mais largas. Puxe forçando a retração das escápulas (remada) com core anti-rotação. Foco em dorsais.',
      media: { gif: 'decline-push-up.gif' },
      ativo: false,
      equipamento: 'push_up_board',
    },
    { repeticoes_iniciante: 8, repeticoes_intermediario: 12, repeticoes_avancado: 15 },
  ),
  withCustomParams(
    {
      slug: 'push-up-board-chest-wide',
      nome: 'Push-Up Board — Peito largo',
      nome_pt: 'Flexão na prancha — Peito largo (vermelho)',
      nivel: 2,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'A',
      modo: 'reps',
      descricao: 'Encaixe as pegadas nos slots vermelhos mais externos (mãos bem abertas). Maior alongamento do peitoral; desça controlado.',
      media: { gif: 'push-up-board-chest-wide.gif' },
      ativo: false,
      equipamento: 'push_up_board',
    },
    { repeticoes_iniciante: 8, repeticoes_intermediario: 12, repeticoes_avancado: 16 },
  ),
  withCustomParams(
    {
      slug: 'push-up-board-decline',
      nome: 'Push-Up Board — Peito declinado',
      nome_pt: 'Flexão na prancha — Peito declinado (vermelho)',
      nivel: 3,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'B',
      modo: 'reps',
      descricao: 'Pegadas nos slots vermelhos com os pés elevados (num apoio). Carga deslocada para o peito superior e ombros.',
      media: { gif: 'push-up-board-decline.gif' },
      ativo: false,
      equipamento: 'push_up_board',
    },
    { repeticoes_iniciante: 6, repeticoes_intermediario: 10, repeticoes_avancado: 14 },
  ),
  withCustomParams(
    {
      slug: 'push-up-board-triceps-diamond',
      nome: 'Push-Up Board — Tríceps diamante',
      nome_pt: 'Flexão na prancha — Tríceps diamante (verde)',
      nivel: 3,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'A',
      modo: 'reps',
      descricao: 'Pegadas nos slots verdes centrais formando um diamante (mãos juntas sob o peito). Cotovelos colados — máxima tensão no tríceps.',
      media: { gif: 'push-up-board-diamond.gif' },
      ativo: false,
      equipamento: 'push_up_board',
    },
    { repeticoes_iniciante: 5, repeticoes_intermediario: 8, repeticoes_avancado: 12 },
  ),
  withCustomParams(
    {
      slug: 'push-up-board-shoulders-pike',
      nome: 'Push-Up Board — Ombros pike',
      nome_pt: 'Flexão na prancha — Ombros pike (azul)',
      nivel: 3,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'B',
      modo: 'reps',
      descricao: 'Pegadas nos slots azuis com o quadril bem alto (posição de "V" invertido). Desça a cabeça entre as mãos — foco total nos deltoides.',
      media: { gif: 'push-up-board-pike.gif' },
      ativo: false,
      equipamento: 'push_up_board',
    },
    { repeticoes_iniciante: 5, repeticoes_intermediario: 8, repeticoes_avancado: 11 },
  ),
  withCustomParams(
    {
      slug: 'push-up-board-back-wide',
      nome: 'Push-Up Board — Costas aberto',
      nome_pt: 'Flexão na prancha — Costas aberto (amarelo)',
      nivel: 3,
      musculo_principal: 'superior',
      musculos_secundarios: ['core', 'obliquos'],
      tempo_recomendado: 30,
      prioridade: 'B',
      modo: 'reps',
      descricao: 'Pegadas nos slots amarelos mais largos e angulados. Puxe forçando a retração das escápulas a cada repetição — dorsais e estabilizadores.',
      media: { gif: 'push-up-board-back-wide.gif' },
      ativo: false,
      equipamento: 'push_up_board',
    },
    { repeticoes_iniciante: 8, repeticoes_intermediario: 12, repeticoes_avancado: 15 },
  ),

  // —— Barra fixa ——
  withCustomParams(
    {
      slug: 'pull-up',
      nome: 'Pull-Up',
      nome_pt: 'Barra fixa — Pronada',
      nivel: 3,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'A',
      modo: 'reps',
      descricao: 'Puxada com pegada pronada — costas e bíceps.',
      media: { gif: 'hanging-knee-raise.gif' },
      ativo: false,
      equipamento: 'pull_up_bar',
    },
    { repeticoes_iniciante: 3, repeticoes_intermediario: 6, repeticoes_avancado: 10 },
  ),
  withCustomParams(
    {
      slug: 'chin-up',
      nome: 'Chin-Up',
      nome_pt: 'Barra fixa — Supinada',
      nivel: 2,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'A',
      modo: 'reps',
      descricao: 'Puxada com pegada supinada — bíceps e dorsais.',
      media: { gif: 'hanging-knee-raise.gif' },
      ativo: false,
      equipamento: 'pull_up_bar',
    },
    { repeticoes_iniciante: 4, repeticoes_intermediario: 8, repeticoes_avancado: 12 },
  ),
  withCustomParams(
    {
      slug: 'dead-hang',
      nome: 'Dead Hang',
      nome_pt: 'Suspensão isométrica',
      nivel: 2,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 45,
      prioridade: 'isometrico',
      modo: 'tempo',
      descricao: 'Suspensão passiva na barra — grip, ombros e core. Segure o tempo indicado.',
      media: { gif: 'hanging-knee-raise.gif' },
      ativo: false,
      equipamento: 'pull_up_bar',
    },
    {
      repeticoes_iniciante: 0,
      repeticoes_intermediario: 0,
      repeticoes_avancado: 0,
      tempo_seg_iniciante: 30,
      tempo_seg_intermediario: 45,
      tempo_seg_avancado: 60,
      descanso_seg_iniciante: 45,
      descanso_seg_intermediario: 35,
      descanso_seg_avancado: 25,
    },
  ),

  // —— Rolinho abdominal ——
  withCustomParams(
    {
      slug: 'ab-wheel-knees',
      nome: 'Ab Wheel — Joelhos',
      nome_pt: 'Rolinho — Joelhos no chão',
      nivel: 2,
      musculo_principal: 'core',
      musculos_secundarios: ['superior'],
      tempo_recomendado: 30,
      prioridade: 'B',
      modo: 'reps',
      descricao: 'Rollout curto com joelhos apoiados — introdução ao rolinho.',
      media: { gif: 'ab-wheel.gif' },
      ativo: false,
      equipamento: 'ab_wheel',
    },
    { repeticoes_iniciante: 6, repeticoes_intermediario: 10, repeticoes_avancado: 14 },
  ),
  withCustomParams(
    {
      slug: 'ab-wheel-standing',
      nome: 'Ab Wheel — Em pé',
      nome_pt: 'Rolinho — Amplitude completa',
      nivel: 4,
      musculo_principal: 'core',
      musculos_secundarios: ['superior'],
      tempo_recomendado: 30,
      prioridade: 'B',
      modo: 'reps',
      descricao: 'Rollout partindo da posição em pé — progressão avançada.',
      media: { gif: 'ab-wheel.gif' },
      ativo: false,
      equipamento: 'ab_wheel',
    },
    { repeticoes_iniciante: 3, repeticoes_intermediario: 5, repeticoes_avancado: 8 },
  ),
];
