import { withCustomParams } from '../../utils/exercise-params.js';
import type { IExercise } from '../../types/index.js';

/** Exercícios gated por equipamento — `ativo: false` até o usuário marcar que possui o item. */
export const equipmentExercises: IExercise[] = [
  // —— Barra fixa ——
  withCustomParams(
    {
      slug: 'pull-up',
      nome: 'Pull-Up',
      nome_pt: 'Barra fixa — Pronada',
      nivel: 3,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'A',
      modo: 'reps',
      descricao: 'Puxada com pegada pronada — costas e bíceps.',
      media: { gif: 'pull-up.gif' },
      ativo: false,
      equipamento: 'pull_up_bar',
    },
    { repeticoes_iniciante: 3, repeticoes_intermediario: 6, repeticoes_avancado: 10 },
  ),
  withCustomParams(
    {
      slug: 'chin-up',
      nome: 'Chin-Up',
      nome_pt: 'Barra fixa — Supinada',
      nivel: 2,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'A',
      modo: 'reps',
      descricao: 'Puxada com pegada supinada — bíceps e dorsais.',
      media: { gif: 'chin-up.gif' },
      ativo: false,
      equipamento: 'pull_up_bar',
    },
    { repeticoes_iniciante: 4, repeticoes_intermediario: 8, repeticoes_avancado: 12 },
  ),
  withCustomParams(
    {
      slug: 'scapular-pull-up',
      nome: 'Scapular Pull-Up',
      nome_pt: 'Barra fixa — Escapular',
      nivel: 2,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 30,
      prioridade: 'A',
      modo: 'reps',
      descricao:
        'Pendurado na barra com braços estendidos, puxe só as escápulas para baixo e para trás (sem dobrar os cotovelos). Ponte entre a suspensão e a barra completa.',
      media: { gif: 'scapular-pull-up.gif' },
      ativo: false,
      equipamento: 'pull_up_bar',
    },
    { repeticoes_iniciante: 5, repeticoes_intermediario: 8, repeticoes_avancado: 12 },
  ),
  withCustomParams(
    {
      slug: 'dead-hang',
      nome: 'Dead Hang',
      nome_pt: 'Suspensão isométrica',
      nivel: 2,
      musculo_principal: 'superior',
      musculos_secundarios: ['core'],
      tempo_recomendado: 45,
      prioridade: 'isometrico',
      modo: 'tempo',
      descricao: 'Suspensão passiva na barra — grip, ombros e core. Segure o tempo indicado.',
      media: { gif: 'dead-hang.gif' },
      ativo: false,
      equipamento: 'pull_up_bar',
    },
    {
      repeticoes_iniciante: 0,
      repeticoes_intermediario: 0,
      repeticoes_avancado: 0,
      tempo_seg_iniciante: 30,
      tempo_seg_intermediario: 45,
      tempo_seg_avancado: 60,
      descanso_seg_iniciante: 45,
      descanso_seg_intermediario: 35,
      descanso_seg_avancado: 25,
    },
  ),

  // —— Rolinho abdominal ——
  withCustomParams(
    {
      slug: 'ab-wheel-knees',
      nome: 'Ab Wheel — Joelhos',
      nome_pt: 'Rolinho — Joelhos no chão',
      nivel: 2,
      musculo_principal: 'core',
      musculos_secundarios: ['superior'],
      tempo_recomendado: 30,
      prioridade: 'B',
      modo: 'reps',
      descricao: 'Rollout curto com joelhos apoiados — introdução ao rolinho.',
      media: { gif: 'ab-wheel-knees.gif' },
      ativo: false,
      equipamento: 'ab_wheel',
    },
    { repeticoes_iniciante: 6, repeticoes_intermediario: 10, repeticoes_avancado: 14 },
  ),
  withCustomParams(
    {
      slug: 'ab-wheel-standing',
      nome: 'Ab Wheel — Em pé',
      nome_pt: 'Rolinho — Amplitude completa',
      nivel: 4,
      musculo_principal: 'core',
      musculos_secundarios: ['superior'],
      tempo_recomendado: 30,
      prioridade: 'B',
      modo: 'reps',
      descricao: 'Rollout partindo da posição em pé — progressão avançada.',
      media: { gif: 'ab-wheel.gif' },
      ativo: false,
      equipamento: 'ab_wheel',
    },
    { repeticoes_iniciante: 3, repeticoes_intermediario: 5, repeticoes_avancado: 8 },
  ),
];
