import type { IWorkoutPreset } from '../../types/index.js';

function preset(
  p: Omit<IWorkoutPreset, 'exercicios'> & {
    slugs: { slug: string; series?: number; modo?: 'tempo' | 'reps'; repeticoes?: number; tempo_seg?: number; descanso_seg?: number }[];
  },
): IWorkoutPreset {
  return {
    nome: p.nome,
    nivel: p.nivel,
    objetivo: p.objetivo,
    ciclo_id: p.ciclo_id,
    descricao: p.descricao,
    recomendado: p.recomendado,
    exercicios: p.slugs.map((s) => ({
      slug: s.slug,
      series: s.series ?? 3,
      modo: s.modo ?? 'reps',
      repeticoes: s.repeticoes,
      tempo_seg: s.tempo_seg,
      descanso_seg: s.descanso_seg ?? 30,
    })),
  };
}

export const workoutPresets: IWorkoutPreset[] = [
  preset({
    nome: 'Ciclo A — Superior (Iniciante)',
    nivel: 'iniciante',
    objetivo: 'definicao',
    ciclo_id: 'A',
    descricao: 'Foco no reto abdominal superior com volume moderado.',
    recomendado: true,
    slugs: [
      { slug: 'crunch', series: 3, repeticoes: 12, descanso_seg: 40 },
      { slug: 'sit-up', series: 3, repeticoes: 10, descanso_seg: 40 },
      { slug: 'toe-touches', series: 3, repeticoes: 12, descanso_seg: 40 },
      { slug: 'stability-ball-crunch', series: 2, repeticoes: 10, descanso_seg: 40 },
      { slug: 'reverse-crunch', series: 3, repeticoes: 10, descanso_seg: 35 },
      { slug: 'incline-push-up', series: 2, repeticoes: 8, descanso_seg: 40 },
      { slug: 'push-up-board-chest', series: 2, repeticoes: 8, descanso_seg: 40 },
    ],
  }),
  preset({
    nome: 'Ciclo A — Superior (Intermediário)',
    nivel: 'intermediario',
    objetivo: 'definicao',
    ciclo_id: 'A',
    descricao: 'Volume maior para abdômen superior.',
    recomendado: true,
    slugs: [
      { slug: 'crunch', series: 4, repeticoes: 14, descanso_seg: 25 },
      { slug: 'jackknife-sit-up', series: 3, repeticoes: 12, descanso_seg: 25 },
      { slug: 'stability-ball-crunch', series: 3, repeticoes: 15, descanso_seg: 25 },
      { slug: 'sit-up', series: 3, repeticoes: 14, descanso_seg: 25 },
      { slug: 'toe-touches', series: 3, repeticoes: 16, descanso_seg: 25 },
      { slug: 'push-up-board-chest-wide', series: 3, repeticoes: 10, descanso_seg: 25 },
      { slug: 'push-up-board-shoulders', series: 3, repeticoes: 8, descanso_seg: 25 },
    ],
  }),
  preset({
    nome: 'Ciclo A — Superior (Avançado)',
    nivel: 'avancado',
    objetivo: 'forca',
    ciclo_id: 'A',
    descricao: 'Alta intensidade para superior.',
    recomendado: true,
    slugs: [
      { slug: 'jackknife-sit-up', series: 4, repeticoes: 10, descanso_seg: 18 },
      { slug: 'ab-wheel', series: 3, repeticoes: 8, descanso_seg: 20 },
      { slug: 'dragon-flag', series: 3, repeticoes: 5, descanso_seg: 25 },
      { slug: 'stability-ball-crunch', series: 4, repeticoes: 12, descanso_seg: 18 },
      { slug: 'crunch', series: 3, repeticoes: 15, descanso_seg: 18 },
      { slug: 'push-up-board-triceps-diamond', series: 3, repeticoes: 8, descanso_seg: 20 },
      { slug: 'push-up-board-decline', series: 3, repeticoes: 8, descanso_seg: 20 },
    ],
  }),
  preset({
    nome: 'Ciclo B — Oblíquos (Iniciante)',
    nivel: 'iniciante',
    objetivo: 'definicao',
    ciclo_id: 'B',
    descricao: 'Ativação lateral segura.',
    recomendado: true,
    slugs: [
      { slug: 'heel-touches', series: 3, repeticoes: 12, descanso_seg: 40 },
      { slug: 'bicycle-crunch', series: 3, repeticoes: 12, descanso_seg: 40 },
      { slug: 'russian-twist', series: 3, repeticoes: 10, descanso_seg: 40 },
      { slug: 'side-plank', series: 2, modo: 'tempo', tempo_seg: 20, descanso_seg: 40 },
      { slug: 'dead-bug', series: 3, repeticoes: 10, descanso_seg: 35 },
    ],
  }),
  preset({
    nome: 'Ciclo B — Oblíquos (Intermediário)',
    nivel: 'intermediario',
    objetivo: 'definicao',
    ciclo_id: 'B',
    descricao: 'Oblíquos com rotação e isometria.',
    recomendado: true,
    slugs: [
      { slug: 'bicycle-crunch', series: 4, repeticoes: 16, descanso_seg: 25 },
      { slug: 'windshield-wipers', series: 3, repeticoes: 10, descanso_seg: 30 },
      { slug: 'side-plank', series: 3, modo: 'tempo', tempo_seg: 30, descanso_seg: 25 },
      { slug: 'russian-twist', series: 3, repeticoes: 14, descanso_seg: 25 },
      { slug: 'heel-touches', series: 3, repeticoes: 16, descanso_seg: 25 },
    ],
  }),
  preset({
    nome: 'Ciclo B — Oblíquos (Avançado)',
    nivel: 'avancado',
    objetivo: 'forca',
    ciclo_id: 'B',
    descricao: 'Oblíquos avançados.',
    recomendado: true,
    slugs: [
      { slug: 'windshield-wipers', series: 4, repeticoes: 12, descanso_seg: 18 },
      { slug: 'copenhagen-plank', series: 3, modo: 'tempo', tempo_seg: 25, descanso_seg: 20 },
      { slug: 'spiderman-plank', series: 3, repeticoes: 12, descanso_seg: 18 },
      { slug: 'bicycle-crunch', series: 4, repeticoes: 14, descanso_seg: 18 },
      { slug: 'side-plank', series: 3, modo: 'tempo', tempo_seg: 25, descanso_seg: 20 },
    ],
  }),
  preset({
    nome: 'Ciclo C — Inferior (Iniciante)',
    nivel: 'iniciante',
    objetivo: 'definicao',
    ciclo_id: 'C',
    descricao: 'Abdômen inferior com controle.',
    recomendado: true,
    slugs: [
      { slug: 'reverse-crunch', series: 3, repeticoes: 12, descanso_seg: 40 },
      { slug: 'leg-raises', series: 3, repeticoes: 10, descanso_seg: 40 },
      { slug: 'flutter-kicks', series: 3, repeticoes: 12, descanso_seg: 40 },
      { slug: 'scissor-kicks', series: 2, repeticoes: 12, descanso_seg: 40 },
      { slug: 'dead-bug', series: 3, repeticoes: 10, descanso_seg: 35 },
    ],
  }),
  preset({
    nome: 'Ciclo C — Inferior (Intermediário)',
    nivel: 'intermediario',
    objetivo: 'resistencia',
    ciclo_id: 'C',
    descricao: 'Resistência do abdômen inferior.',
    recomendado: true,
    slugs: [
      { slug: 'leg-raises', series: 4, repeticoes: 12, descanso_seg: 25 },
      { slug: 'scissor-kicks', series: 3, repeticoes: 16, descanso_seg: 25 },
      { slug: 'flutter-kicks', series: 3, repeticoes: 16, descanso_seg: 25 },
      { slug: 'reverse-crunch', series: 3, repeticoes: 14, descanso_seg: 25 },
      { slug: 'hanging-knee-raise', series: 3, repeticoes: 8, descanso_seg: 30 },
    ],
  }),
  preset({
    nome: 'Ciclo C — Inferior (Avançado)',
    nivel: 'avancado',
    objetivo: 'forca',
    ciclo_id: 'C',
    descricao: 'Inferior avançado com barra.',
    recomendado: true,
    slugs: [
      { slug: 'hanging-knee-raise', series: 4, repeticoes: 10, descanso_seg: 20 },
      { slug: 'leg-raises', series: 4, repeticoes: 12, descanso_seg: 18 },
      { slug: 'v-hold', series: 3, modo: 'tempo', tempo_seg: 30, descanso_seg: 25 },
      { slug: 'flutter-kicks', series: 4, repeticoes: 14, descanso_seg: 18 },
      { slug: 'dragon-flag', series: 2, repeticoes: 4, descanso_seg: 25 },
    ],
  }),
  preset({
    nome: 'Ciclo D — Core (Iniciante)',
    nivel: 'iniciante',
    objetivo: 'manutencao',
    ciclo_id: 'D',
    descricao: 'Estabilidade fundamental.',
    recomendado: true,
    slugs: [
      { slug: 'plank', series: 3, modo: 'tempo', tempo_seg: 25, descanso_seg: 40 },
      { slug: 'dead-bug', series: 3, repeticoes: 10, descanso_seg: 40 },
      { slug: 'thread-the-needle', series: 3, repeticoes: 10, descanso_seg: 40 },
      { slug: 'side-plank', series: 2, modo: 'tempo', tempo_seg: 20, descanso_seg: 40 },
      { slug: 'heel-touches', series: 2, repeticoes: 12, descanso_seg: 40 },
    ],
  }),
  preset({
    nome: 'Ciclo D — Core (Intermediário)',
    nivel: 'intermediario',
    objetivo: 'resistencia',
    ciclo_id: 'D',
    descricao: 'Core com isometria e controle.',
    recomendado: true,
    slugs: [
      { slug: 'plank', series: 3, modo: 'tempo', tempo_seg: 35, descanso_seg: 25 },
      { slug: 'dead-bug', series: 4, repeticoes: 12, descanso_seg: 25 },
      { slug: 'hollow-hold', series: 3, modo: 'tempo', tempo_seg: 30, descanso_seg: 30 },
      { slug: 'spiderman-plank', series: 3, repeticoes: 10, descanso_seg: 25 },
      { slug: 'thread-the-needle', series: 3, repeticoes: 12, descanso_seg: 25 },
    ],
  }),
  preset({
    nome: 'Ciclo D — Core (Avançado)',
    nivel: 'avancado',
    objetivo: 'forca',
    ciclo_id: 'D',
    descricao: 'Core avançado isométrico.',
    recomendado: true,
    slugs: [
      { slug: 'hollow-hold', series: 4, modo: 'tempo', tempo_seg: 40, descanso_seg: 20 },
      { slug: 'l-sit', series: 3, modo: 'tempo', tempo_seg: 20, descanso_seg: 25 },
      { slug: 'v-hold', series: 3, modo: 'tempo', tempo_seg: 35, descanso_seg: 20 },
      { slug: 'copenhagen-plank', series: 3, modo: 'tempo', tempo_seg: 25, descanso_seg: 20 },
      { slug: 'ab-wheel', series: 3, repeticoes: 6, descanso_seg: 25 },
    ],
  }),
  preset({
    nome: 'Ciclo E — Completo (Iniciante)',
    nivel: 'iniciante',
    objetivo: 'resistencia',
    ciclo_id: 'E',
    descricao: 'Circuito leve de corpo inteiro.',
    recomendado: true,
    slugs: [
      { slug: 'mountain-climbers', series: 3, modo: 'tempo', tempo_seg: 25, descanso_seg: 40 },
      { slug: 'plank-jacks', series: 3, modo: 'tempo', tempo_seg: 20, descanso_seg: 40 },
      { slug: 'bicycle-crunch', series: 3, repeticoes: 12, descanso_seg: 40 },
      { slug: 'crunch', series: 3, repeticoes: 12, descanso_seg: 40 },
      { slug: 'plank', series: 2, modo: 'tempo', tempo_seg: 20, descanso_seg: 40 },
      { slug: 'push-up', series: 2, repeticoes: 8, descanso_seg: 40 },
    ],
  }),
  preset({
    nome: 'Ciclo E — Completo (Intermediário)',
    nivel: 'intermediario',
    objetivo: 'resistencia',
    ciclo_id: 'E',
    descricao: 'Circuito metabólico moderado.',
    recomendado: true,
    slugs: [
      { slug: 'mountain-climbers', series: 4, modo: 'tempo', tempo_seg: 30, descanso_seg: 25 },
      { slug: 'burpee', series: 3, repeticoes: 10, descanso_seg: 30 },
      { slug: 'bear-crawl', series: 3, modo: 'tempo', tempo_seg: 25, descanso_seg: 25 },
      { slug: 'bicycle-crunch', series: 3, repeticoes: 14, descanso_seg: 25 },
      { slug: 'leg-raises', series: 3, repeticoes: 12, descanso_seg: 25 },
    ],
  }),
  preset({
    nome: 'Ciclo E — Completo (Avançado)',
    nivel: 'avancado',
    objetivo: 'forca',
    ciclo_id: 'E',
    descricao: 'Alta intensidade full core.',
    recomendado: true,
    slugs: [
      { slug: 'burpee', series: 4, repeticoes: 10, descanso_seg: 18 },
      { slug: 'mountain-climbers', series: 4, modo: 'tempo', tempo_seg: 40, descanso_seg: 18 },
      { slug: 'plank-jacks', series: 4, modo: 'tempo', tempo_seg: 35, descanso_seg: 18 },
      { slug: 'hanging-knee-raise', series: 3, repeticoes: 10, descanso_seg: 20 },
      { slug: 'ab-wheel', series: 3, repeticoes: 8, descanso_seg: 20 },
    ],
  }),
];
