import type { AchievementIcon } from '@/types';
import {
  IconBarbell,
  IconBolt,
  IconCalendar,
  IconClock,
  IconCrown,
  IconDiamond,
  IconDroplet,
  IconFlame,
  IconHeart,
  IconMedal,
  IconMoon,
  IconRocket,
  IconShield,
  IconSnowflake,
  IconSparkles,
  IconStar,
  IconSun,
  IconTarget,
  IconTrophy,
  type Icon,
} from '@tabler/icons-react';

/** Mapa único de ícone → componente Tabler — fonte compartilhada por conquistas,
    atividades e cosméticos. */
export const ACHIEVEMENT_ICON_COMPONENTS: Record<AchievementIcon, Icon> = {
  medal: IconMedal,
  flame: IconFlame,
  trophy: IconTrophy,
  zap: IconBolt,
  star: IconStar,
  target: IconTarget,
  crown: IconCrown,
  sun: IconSun,
  moon: IconMoon,
  calendar: IconCalendar,
  clock: IconClock,
  gem: IconDiamond,
  rocket: IconRocket,
  dumbbell: IconBarbell,
  heart: IconHeart,
  shield: IconShield,
  droplet: IconDroplet,
  sparkles: IconSparkles,
  snowflake: IconSnowflake,
};
