import type { CosmeticDefinition } from './types/index.js';

/**
 * Catálogo único de cosméticos (molduras de loja, títulos, sons, efeitos, banners).
 * Fonte de verdade compartilhada entre server e client — o client deriva daqui em vez
 * de manter um espelho manual (que ficava dessincronizado e sumia títulos novos).
 * Desbloqueio só por conquista/código/evento (sons são a exceção comprável por moedas).
 */

/**
 * Molduras Bronze/Ouro por nível saíram do catálogo (2026-07-21) — só existem
 * as versões de pódio semanal (sistema MolduraId em services/molduras.ts).
 * Contas antigas têm os ids limpos em syncShopUnlocks.
 */
export const REMOVED_COSMETIC_IDS = ['borda_bronze', 'borda_ouro'] as const;

export const COSMETICS: CosmeticDefinition[] = [
  {
    id: 'borda_basica',
    kind: 'moldura_loja',
    nome: 'Básica',
    descricao: 'Moldura padrão verde do Evolyn.',
    icon: 'shield',
    raridade: 'comum',
    unlock: { tipo: 'gratis' },
  },
  {
    id: 'borda_prata',
    kind: 'moldura_loja',
    nome: 'Prata',
    descricao: 'Brilho prateado ao atingir o nível 10.',
    icon: 'star',
    raridade: 'raro',
    unlock: { tipo: 'nivel', nivel_min: 10 },
  },
  {
    id: 'borda_esmeralda',
    kind: 'moldura_loja',
    nome: 'Esmeralda',
    descricao: 'Um mês inteiro de chama acesa: 30 dias de streak.',
    icon: 'gem',
    raridade: 'raro',
    unlock: { tipo: 'conquista', conquista_id: 'streak_30' },
  },
  {
    id: 'borda_ametista',
    kind: 'moldura_loja',
    nome: 'Ametista',
    descricao: 'Reservada a quem possui qualquer item Mítico.',
    icon: 'moon',
    raridade: 'epico',
    unlock: { tipo: 'item_mitico' },
  },
  {
    id: 'borda_fogo',
    kind: 'moldura_loja',
    nome: 'Fogo',
    descricao: 'Reúna o trio Flamejante: Magia de Fogo, Arco Flamejante e Espada Flamejante.',
    icon: 'flame',
    raridade: 'epico',
    unlock: { tipo: 'conjunto_flamejante' },
  },
  {
    id: 'borda_imparavel',
    kind: 'moldura_loja',
    nome: 'Imparável',
    descricao: '160 dias de streak — quase impossível.',
    icon: 'shield',
    raridade: 'lendario',
    unlock: { tipo: 'streak', streak_dias: 160 },
  },
  {
    id: 'borda_lendario',
    kind: 'moldura_loja',
    nome: 'Lendária',
    descricao: '360 dias de streak — um ano de lenda.',
    icon: 'gem',
    raridade: 'lendario',
    unlock: { tipo: 'streak', streak_dias: 360 },
  },

  // —— Títulos ——
  {
    id: 'titulo_eu_sou_heroi',
    kind: 'titulo',
    nome: 'Eu sou herói',
    descricao: 'Título exclusivo do código presente Evolyn.',
    icon: 'crown',
    raridade: 'lendario',
    unlock: { tipo: 'codigo' },
  },
  {
    id: 'titulo_guerreiro',
    kind: 'titulo',
    nome: 'Guerreiro do core',
    descricao: 'Desbloqueado no nível 5.',
    icon: 'shield',
    raridade: 'raro',
    unlock: { tipo: 'nivel', nivel_min: 5 },
  },
  {
    id: 'titulo_imparavel',
    kind: 'titulo',
    nome: 'Imparável',
    descricao: 'Conquista: 30 dias de streak.',
    icon: 'flame',
    raridade: 'epico',
    unlock: { tipo: 'conquista', conquista_id: 'streak_30' },
  },
  {
    id: 'titulo_lenda',
    kind: 'titulo',
    nome: 'Lenda viva',
    descricao: 'Compre na loja com Folhas.',
    icon: 'gem',
    raridade: 'lendario',
    unlock: { tipo: 'moedas', preco_moedas: 85 },
  },
  {
    id: 'titulo_atleta',
    kind: 'titulo',
    nome: 'Atleta dedicado',
    descricao: 'Alcance o nível 3.',
    icon: 'medal',
    raridade: 'comum',
    unlock: { tipo: 'nivel', nivel_min: 3 },
  },
  {
    id: 'titulo_campeao',
    kind: 'titulo',
    nome: 'Campeão do core',
    descricao: 'Nível 10 — elite dos treinos.',
    icon: 'trophy',
    raridade: 'epico',
    unlock: { tipo: 'nivel', nivel_min: 10 },
  },
  {
    id: 'titulo_mestre',
    kind: 'titulo',
    nome: 'Mestre do abdômen',
    descricao: 'Nível 15 — referência na arena.',
    icon: 'crown',
    raridade: 'lendario',
    unlock: { tipo: 'nivel', nivel_min: 15 },
  },
  {
    id: 'titulo_guardiao',
    kind: 'titulo',
    nome: 'Guardião da chama',
    descricao: '14 dias seguidos treinando.',
    icon: 'flame',
    raridade: 'raro',
    unlock: { tipo: 'conquista', conquista_id: 'streak_14' },
  },
  {
    id: 'titulo_veterano',
    kind: 'titulo',
    nome: 'Veterano',
    descricao: '100 treinos concluídos.',
    icon: 'shield',
    raridade: 'epico',
    unlock: { tipo: 'conquista', conquista_id: 'treinos_100' },
  },
  {
    id: 'titulo_fenix',
    kind: 'titulo',
    nome: 'Fênix',
    descricao: '60 dias de streak — renasce das cinzas.',
    icon: 'flame',
    raridade: 'lendario',
    unlock: { tipo: 'conquista', conquista_id: 'streak_60' },
  },
  {
    id: 'titulo_madrugador',
    kind: 'titulo',
    nome: 'Madrugador',
    descricao: 'Conquista: treino antes das 7h.',
    icon: 'star',
    raridade: 'raro',
    unlock: { tipo: 'conquista', conquista_id: 'early_bird' },
  },
  {
    id: 'titulo_coruja',
    kind: 'titulo',
    nome: 'Coruja noturna',
    descricao: 'Conquista: treino após as 22h.',
    icon: 'moon',
    raridade: 'raro',
    unlock: { tipo: 'conquista', conquista_id: 'night_owl' },
  },
  {
    id: 'titulo_membro_familia',
    kind: 'titulo',
    nome: 'Membro da Família',
    descricao: 'Exclusivo de quem entrou no Discord do Evolyn.',
    icon: 'heart',
    raridade: 'raro',
    unlock: { tipo: 'codigo' },
  },

  // —— Sons ——
  {
    id: 'som_classico',
    kind: 'som',
    nome: 'Clássico',
    descricao: 'Sons suaves padrão do Evolyn.',
    icon: 'zap',
    raridade: 'comum',
    unlock: { tipo: 'gratis' },
  },
  {
    id: 'som_suave',
    kind: 'som',
    nome: 'Suave',
    descricao: 'Tons calmos para treinos longos.',
    icon: 'star',
    raridade: 'comum',
    unlock: { tipo: 'gratis' },
  },
  {
    id: 'som_chime',
    kind: 'som',
    nome: 'Sino',
    descricao: 'Campainhas leves ao concluir séries.',
    icon: 'zap',
    raridade: 'comum',
    unlock: { tipo: 'gratis' },
  },
  {
    id: 'som_pop',
    kind: 'som',
    nome: 'Pop',
    descricao: 'Cliques curtos e divertidos.',
    icon: 'star',
    raridade: 'comum',
    unlock: { tipo: 'moedas', preco_moedas: 1 },
  },
  {
    id: 'som_arcade',
    kind: 'som',
    nome: 'Arcade',
    descricao: 'Beeps retrô estilo fliperama.',
    icon: 'rocket',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 3 },
  },
  {
    id: 'som_retro',
    kind: 'som',
    nome: 'Retro',
    descricao: 'Sintetizador old-school.',
    icon: 'rocket',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 3 },
  },
  {
    id: 'som_pixel',
    kind: 'som',
    nome: 'Pixel',
    descricao: 'Tons quadrados de jogos 8-bit.',
    icon: 'star',
    raridade: 'epico',
    unlock: { tipo: 'moedas', preco_moedas: 6 },
  },
  {
    id: 'som_metal',
    kind: 'som',
    nome: 'Metal',
    descricao: 'Impactos metálicos de RPG.',
    icon: 'shield',
    raridade: 'epico',
    unlock: { tipo: 'moedas', preco_moedas: 6 },
  },
  {
    id: 'som_epico',
    kind: 'som',
    nome: 'Épico',
    descricao: 'Fanfarras heroicas na vitória.',
    icon: 'trophy',
    raridade: 'lendario',
    unlock: { tipo: 'moedas', preco_moedas: 9 },
  },
  {
    id: 'som_cristal',
    kind: 'som',
    nome: 'Cristal',
    descricao: 'Cristais brilhantes a cada conquista.',
    icon: 'gem',
    raridade: 'comum',
    unlock: { tipo: 'gratis' },
  },
  {
    id: 'som_zen',
    kind: 'som',
    nome: 'Zen',
    descricao: 'Tons minimalistas para foco total.',
    icon: 'moon',
    raridade: 'comum',
    unlock: { tipo: 'gratis' },
  },
  {
    id: 'som_bolha',
    kind: 'som',
    nome: 'Bolha',
    descricao: 'Pops leves e divertidos.',
    icon: 'heart',
    raridade: 'comum',
    unlock: { tipo: 'moedas', preco_moedas: 2 },
  },
  {
    id: 'som_8bit',
    kind: 'som',
    nome: '8-Bit',
    descricao: 'Beeps de fliperama retrô.',
    icon: 'rocket',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 4 },
  },
  {
    id: 'som_treino',
    kind: 'som',
    nome: 'Pump',
    descricao: 'Energia de treino intenso.',
    icon: 'dumbbell',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 4 },
  },
  {
    id: 'som_boss',
    kind: 'som',
    nome: 'Boss',
    descricao: 'Impactos graves de chefe de RPG.',
    icon: 'shield',
    raridade: 'epico',
    unlock: { tipo: 'moedas', preco_moedas: 7 },
  },
  {
    id: 'som_noturno',
    kind: 'som',
    nome: 'Noturno',
    descricao: 'Atmosfera misteriosa para a noite.',
    icon: 'moon',
    raridade: 'epico',
    unlock: { tipo: 'moedas', preco_moedas: 7 },
  },
  {
    id: 'som_vitoria',
    kind: 'som',
    nome: 'Vitória',
    descricao: 'Fanfarra triunfal ao finalizar.',
    icon: 'crown',
    raridade: 'lendario',
    unlock: { tipo: 'moedas', preco_moedas: 10 },
  },

  // —— Efeitos visuais ——
  {
    id: 'efeito_padrao',
    kind: 'efeito',
    nome: 'Padrão',
    descricao: 'Celebração clássica ao concluir treinos.',
    icon: 'medal',
    raridade: 'comum',
    unlock: { tipo: 'gratis' },
  },
  {
    id: 'efeito_confete',
    kind: 'efeito',
    nome: 'Confete',
    descricao: 'Chuva colorida na vitória.',
    icon: 'star',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 50 },
  },
  {
    id: 'efeito_raios',
    kind: 'efeito',
    nome: 'Raios',
    descricao: 'Explosão elétrica de energia.',
    icon: 'zap',
    raridade: 'epico',
    unlock: { tipo: 'moedas', preco_moedas: 70 },
  },
  {
    id: 'efeito_fogo',
    kind: 'efeito',
    nome: 'Chamas',
    descricao: 'Conquista: 7 dias de streak.',
    icon: 'flame',
    raridade: 'epico',
    unlock: { tipo: 'conquista', conquista_id: 'streak_7' },
  },
  {
    id: 'efeito_agua',
    kind: 'efeito',
    nome: 'Onda Azul',
    descricao: 'Chuva de pixels aquáticos no perfil.',
    icon: 'droplet',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 85 },
  },
  {
    id: 'efeito_glitch',
    kind: 'efeito',
    nome: 'Quebra de Tela',
    descricao: 'Glitch pixelado de alta raridade.',
    icon: 'sparkles',
    raridade: 'lendario',
    unlock: { tipo: 'moedas', preco_moedas: 180 },
  },

  {
    id: 'borda_admin',
    kind: 'moldura_loja',
    nome: 'Guardião de Evolyn',
    descricao: 'Moldura exclusiva de quem administra o reino.',
    icon: 'crown',
    raridade: 'secreto',
    unlock: { tipo: 'codigo' },
  },

  {
    id: 'titulo_dono_do_jogo',
    kind: 'titulo',
    nome: 'Dono do Jogo',
    descricao: 'Título lendário raríssimo — brilha em cores fortes.',
    icon: 'crown',
    raridade: 'lendario',
    unlock: { tipo: 'codigo' },
  },

  {
    id: 'fundo_padrao',
    kind: 'banner',
    nome: 'Padrão',
    descricao: 'Banner clássico do card de jogador.',
    icon: 'star',
    raridade: 'comum',
    unlock: { tipo: 'gratis' },
  },
  {
    id: 'fundo_aurora',
    kind: 'banner',
    nome: 'Aurora',
    descricao: 'Aurora boreal sobre montanhas noturnas.',
    icon: 'gem',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 120 },
  },
  {
    id: 'fundo_vulcao',
    kind: 'banner',
    nome: 'Vulcão',
    descricao: 'Vulcão em erupção com rios de lava.',
    icon: 'flame',
    raridade: 'epico',
    unlock: { tipo: 'moedas', preco_moedas: 200 },
  },
  {
    id: 'fundo_galaxia',
    kind: 'banner',
    nome: 'Galáxia',
    descricao: 'Cosmos profundo com estrelas cintilantes.',
    icon: 'moon',
    raridade: 'lendario',
    unlock: { tipo: 'moedas', preco_moedas: 743 },
  },
  {
    id: 'fundo_dojo',
    kind: 'banner',
    nome: 'Dojo',
    descricao: 'Tatame e paredes de shoji sob luz quente de lanterna.',
    icon: 'shield',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 140 },
  },
  {
    id: 'fundo_floresta',
    kind: 'banner',
    nome: 'Floresta',
    descricao: 'Trilha entre árvores ao entardecer.',
    icon: 'gem',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 155 },
  },
  {
    id: 'fundo_praia',
    kind: 'banner',
    nome: 'Praia',
    descricao: 'Areia, mar e palmeiras em pixel art.',
    icon: 'star',
    raridade: 'comum',
    unlock: { tipo: 'moedas', preco_moedas: 85 },
  },
  {
    id: 'fundo_templo',
    kind: 'banner',
    nome: 'Templo',
    descricao: 'Ruínas antigas sob o luar.',
    icon: 'moon',
    raridade: 'epico',
    unlock: { tipo: 'moedas', preco_moedas: 210 },
  },
  {
    id: 'fundo_neon',
    kind: 'banner',
    nome: 'Neon City',
    descricao: 'Cidade cyberpunk com letreiros brilhantes.',
    icon: 'zap',
    raridade: 'epico',
    unlock: { tipo: 'moedas', preco_moedas: 245 },
  },
  {
    id: 'fundo_oceano',
    kind: 'banner',
    nome: 'Oceano',
    descricao: 'Mar profundo com reflexos de sol na superfície.',
    icon: 'droplet',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 150 },
  },
  {
    id: 'fundo_ceu',
    kind: 'banner',
    nome: 'Céu',
    descricao: 'Nuvens macias sob um céu azul claro.',
    icon: 'sun',
    raridade: 'comum',
    unlock: { tipo: 'moedas', preco_moedas: 90 },
  },
  {
    id: 'fundo_montanhas',
    kind: 'banner',
    nome: 'Montanhas',
    descricao: 'Picos nevados em camadas contra o céu do amanhecer.',
    icon: 'shield',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 160 },
  },
  {
    id: 'fundo_nevasca',
    kind: 'banner',
    nome: 'Nevasca',
    descricao: 'Neve densa varrendo uma paisagem gelada.',
    icon: 'snowflake',
    raridade: 'raro',
    unlock: { tipo: 'moedas', preco_moedas: 220 },
  },
  {
    id: 'fundo_brasil',
    kind: 'banner',
    nome: 'Brasil',
    descricao: 'Verde e amarelo em homenagem ao hexacampeonato.',
    icon: 'star',
    raridade: 'epico',
    unlock: { tipo: 'codigo' },
  },
];

export const COSMETIC_BY_ID: Record<string, CosmeticDefinition> = Object.fromEntries(
  COSMETICS.map((item) => [item.id, item]),
);

export const DEFAULT_BORDA_ID = 'borda_basica';
