export type AfkSkillBranch = 'arco' | 'espada' | 'magia' | 'sobrevivencia' | 'fortuna';

export type AfkSkillEffect =
  | 'bow_damage_pct'
  | 'bow_crit_pct'
  | 'sword_damage_pct'
  | 'sword_crit_pct'
  | 'crit_damage_pct'
  | 'magic_damage_pct'
  | 'spell_drop_pct'
  | 'hero_hp_pct'
  | 'search_reduction_ms'
  | 'defeat_reduction_ms'
  | 'drop_chance_pct';

export interface AfkSkillNodeDefinition {
  id: string;
  branch: AfkSkillBranch;
  name: string;
  description: string;
  cost: number;
  requires: readonly string[];
  effect: AfkSkillEffect;
  value: number;
  x: number;
  y: number;
}

export const AFK_SKILL_NODES: readonly AfkSkillNodeDefinition[] = [
  {
    id: 'core_instinct',
    branch: 'sobrevivencia',
    name: 'Instinto',
    description: '+2% de vida.',
    cost: 1,
    requires: [],
    effect: 'hero_hp_pct',
    value: 2,
    x: 50,
    y: 50,
  },
  {
    id: 'bow_focus_1',
    branch: 'arco',
    name: 'Mira Serena',
    description: '+1% de dano com arco.',
    cost: 1,
    requires: ['core_instinct'],
    effect: 'bow_damage_pct',
    value: 1,
    x: 40,
    y: 45,
  },
  {
    id: 'sword_focus_1',
    branch: 'espada',
    name: 'Pulso Firme',
    description: '+1% de dano com espada.',
    cost: 1,
    requires: ['core_instinct'],
    effect: 'sword_damage_pct',
    value: 1,
    x: 60,
    y: 45,
  },
  {
    id: 'magic_focus_1',
    branch: 'magia',
    name: 'Centelha Arcana',
    description: '+1,5% de dano mágico.',
    cost: 1,
    requires: ['core_instinct'],
    effect: 'magic_damage_pct',
    value: 1.5,
    x: 40,
    y: 57,
  },
  {
    id: 'vitality_1',
    branch: 'sobrevivencia',
    name: 'Fôlego',
    description: '+3% de vida.',
    cost: 1,
    requires: ['core_instinct'],
    effect: 'hero_hp_pct',
    value: 3,
    x: 50,
    y: 40,
  },
  {
    id: 'bow_crit_1',
    branch: 'arco',
    name: 'Olho do Vento',
    description: '+0,2% de crítico com arco.',
    cost: 2,
    requires: ['bow_focus_1'],
    effect: 'bow_crit_pct',
    value: 0.2,
    x: 33,
    y: 39,
  },
  {
    id: 'bow_focus_2',
    branch: 'arco',
    name: 'Tensão Perfeita',
    description: '+1,5% de dano com arco.',
    cost: 2,
    requires: ['bow_focus_1'],
    effect: 'bow_damage_pct',
    value: 1.5,
    x: 32,
    y: 49,
  },
  {
    id: 'sword_crit_1',
    branch: 'espada',
    name: 'Abertura',
    description: '+0,15% de crítico com espada.',
    cost: 2,
    requires: ['sword_focus_1'],
    effect: 'sword_crit_pct',
    value: 0.15,
    x: 67,
    y: 39,
  },
  {
    id: 'sword_crit_damage',
    branch: 'espada',
    name: 'Golpe Decisivo',
    description: '+2% de dano crítico.',
    cost: 2,
    requires: ['sword_crit_1'],
    effect: 'crit_damage_pct',
    value: 2,
    x: 68,
    y: 49,
  },
  {
    id: 'magic_focus_2',
    branch: 'magia',
    name: 'Canalização',
    description: '+2% de dano mágico.',
    cost: 2,
    requires: ['magic_focus_1'],
    effect: 'magic_damage_pct',
    value: 2,
    x: 33,
    y: 63,
  },
  {
    id: 'spell_fortune',
    branch: 'magia',
    name: 'Eco Místico',
    description: '+0,2% na chance de magia.',
    cost: 3,
    requires: ['magic_focus_2'],
    effect: 'spell_drop_pct',
    value: 0.2,
    x: 32,
    y: 73,
  },
  {
    id: 'search_1',
    branch: 'fortuna',
    name: 'Rastreador',
    description: '-150ms na procura.',
    cost: 1,
    requires: ['core_instinct'],
    effect: 'search_reduction_ms',
    value: 150,
    x: 60,
    y: 57,
  },
  {
    id: 'search_2',
    branch: 'fortuna',
    name: 'Caçador de Rotas',
    description: '-250ms na procura.',
    cost: 2,
    requires: ['search_1'],
    effect: 'search_reduction_ms',
    value: 250,
    x: 67,
    y: 63,
  },
  {
    id: 'vitality_2',
    branch: 'sobrevivencia',
    name: 'Coração de Abdoria',
    description: '+5% de vida.',
    cost: 2,
    requires: ['vitality_1'],
    effect: 'hero_hp_pct',
    value: 5,
    x: 46,
    y: 32,
  },
  {
    id: 'regen_1',
    branch: 'sobrevivencia',
    name: 'Levantar',
    description: '-0,5s derrotado.',
    cost: 2,
    requires: ['vitality_1'],
    effect: 'defeat_reduction_ms',
    value: 500,
    x: 58,
    y: 39,
  },
  {
    id: 'regen_2',
    branch: 'sobrevivencia',
    name: 'Indomável',
    description: '-0,75s derrotado.',
    cost: 3,
    requires: ['regen_1', 'vitality_2'],
    effect: 'defeat_reduction_ms',
    value: 750,
    x: 60,
    y: 31,
  },
  {
    id: 'luck_1',
    branch: 'fortuna',
    name: 'Brilho Raro',
    description: '+0,05% de chance de drop.',
    cost: 3,
    requires: ['search_1'],
    effect: 'drop_chance_pct',
    value: 0.05,
    x: 67,
    y: 74,
  },
  {
    id: 'luck_2',
    branch: 'fortuna',
    name: 'Destino Favorável',
    description: '+0,1% de chance de drop.',
    cost: 5,
    requires: ['luck_1', 'search_2'],
    effect: 'drop_chance_pct',
    value: 0.1,
    x: 76,
    y: 70,
  },
  {
    id: 'bow_precision_2',
    branch: 'arco',
    name: 'Flecha Silenciosa',
    description: '+0,25% de crítico com arco.',
    cost: 3,
    requires: ['bow_crit_1'],
    effect: 'bow_crit_pct',
    value: 0.25,
    x: 25,
    y: 34,
  },
  {
    id: 'bow_mastery',
    branch: 'arco',
    name: 'Vento Cortante',
    description: '+2% de dano com arco.',
    cost: 4,
    requires: ['bow_precision_2', 'bow_focus_2'],
    effect: 'bow_damage_pct',
    value: 2,
    x: 24,
    y: 44,
  },
  {
    id: 'sword_edge_2',
    branch: 'espada',
    name: 'Fio Ancestral',
    description: '+2% de dano com espada.',
    cost: 3,
    requires: ['sword_crit_damage'],
    effect: 'sword_damage_pct',
    value: 2,
    x: 75,
    y: 33,
  },
  {
    id: 'sword_mastery',
    branch: 'espada',
    name: 'Dança das Lâminas',
    description: '+0,25% de crítico com espada.',
    cost: 4,
    requires: ['sword_edge_2'],
    effect: 'sword_crit_pct',
    value: 0.25,
    x: 76,
    y: 43,
  },
  {
    id: 'magic_fortune_2',
    branch: 'magia',
    name: 'Runa Ressonante',
    description: '+0,25% na chance de magia.',
    cost: 4,
    requires: ['spell_fortune'],
    effect: 'spell_drop_pct',
    value: 0.25,
    x: 24,
    y: 78,
  },
  {
    id: 'magic_mastery',
    branch: 'magia',
    name: 'Núcleo Arcano',
    description: '+2,5% de dano mágico.',
    cost: 5,
    requires: ['magic_fortune_2'],
    effect: 'magic_damage_pct',
    value: 2.5,
    x: 24,
    y: 67,
  },
  {
    id: 'vitality_3',
    branch: 'sobrevivencia',
    name: 'Casca Viva',
    description: '+4% de vida.',
    cost: 3,
    requires: ['vitality_2'],
    effect: 'hero_hp_pct',
    value: 4,
    x: 43,
    y: 24,
  },
  {
    id: 'regen_3',
    branch: 'sobrevivencia',
    name: 'Segundo Fôlego',
    description: '-0,75s derrotado.',
    cost: 4,
    requires: ['regen_2', 'vitality_3'],
    effect: 'defeat_reduction_ms',
    value: 750,
    x: 62,
    y: 23,
  },
  {
    id: 'search_3',
    branch: 'fortuna',
    name: 'Olhos na Trilha',
    description: '-300ms na procura.',
    cost: 4,
    requires: ['search_2'],
    effect: 'search_reduction_ms',
    value: 300,
    x: 75,
    y: 59,
  },
  {
    id: 'luck_3',
    branch: 'fortuna',
    name: 'Sopro do Destino',
    description: '+0,1% de chance de drop.',
    cost: 6,
    requires: ['luck_2', 'search_3'],
    effect: 'drop_chance_pct',
    value: 0.1,
    x: 84,
    y: 66,
  },
  {
    id: 'bow_focus_3',
    branch: 'arco',
    name: 'Cadência do Falcão',
    description: '+1,5% de dano com arco.',
    cost: 4,
    requires: ['bow_mastery'],
    effect: 'bow_damage_pct',
    value: 1.5,
    x: 16,
    y: 49,
  },
  {
    id: 'bow_crit_3',
    branch: 'arco',
    name: 'Ponto de Ruptura',
    description: '+0,2% de crítico com arco.',
    cost: 4,
    requires: ['bow_mastery'],
    effect: 'bow_crit_pct',
    value: 0.2,
    x: 16,
    y: 39,
  },
  {
    id: 'bow_focus_4',
    branch: 'arco',
    name: 'Arco da Tempestade',
    description: '+2% de dano com arco.',
    cost: 5,
    requires: ['bow_focus_3'],
    effect: 'bow_damage_pct',
    value: 2,
    x: 8,
    y: 52,
  },
  {
    id: 'bow_crit_4',
    branch: 'arco',
    name: 'Olhar do Predador',
    description: '+0,25% de crítico com arco.',
    cost: 5,
    requires: ['bow_crit_3'],
    effect: 'bow_crit_pct',
    value: 0.25,
    x: 8,
    y: 35,
  },
  {
    id: 'bow_legacy',
    branch: 'arco',
    name: 'Mestre dos Ventos',
    description: '+2,5% de dano com arco.',
    cost: 6,
    requires: ['bow_focus_4', 'bow_crit_4'],
    effect: 'bow_damage_pct',
    value: 2.5,
    x: 3,
    y: 44,
  },
  {
    id: 'sword_edge_3',
    branch: 'espada',
    name: 'Ritmo do Duelista',
    description: '+1,5% de dano com espada.',
    cost: 4,
    requires: ['sword_mastery'],
    effect: 'sword_damage_pct',
    value: 1.5,
    x: 84,
    y: 48,
  },
  {
    id: 'sword_crit_2',
    branch: 'espada',
    name: 'Brecha Perfeita',
    description: '+0,2% de crítico com espada.',
    cost: 4,
    requires: ['sword_mastery'],
    effect: 'sword_crit_pct',
    value: 0.2,
    x: 84,
    y: 37,
  },
  {
    id: 'sword_edge_4',
    branch: 'espada',
    name: 'Lâmina da Aurora',
    description: '+2% de dano com espada.',
    cost: 5,
    requires: ['sword_edge_3'],
    effect: 'sword_damage_pct',
    value: 2,
    x: 92,
    y: 50,
  },
  {
    id: 'sword_crit_3',
    branch: 'espada',
    name: 'Instante Fatal',
    description: '+0,25% de crítico com espada.',
    cost: 5,
    requires: ['sword_crit_2'],
    effect: 'sword_crit_pct',
    value: 0.25,
    x: 92,
    y: 32,
  },
  {
    id: 'sword_legacy',
    branch: 'espada',
    name: 'Mestre das Lâminas',
    description: '+2,5% de dano com espada.',
    cost: 6,
    requires: ['sword_edge_4', 'sword_crit_3'],
    effect: 'sword_damage_pct',
    value: 2.5,
    x: 97,
    y: 41,
  },
  {
    id: 'magic_focus_3',
    branch: 'magia',
    name: 'Fluxo Etéreo',
    description: '+1,5% de dano mágico.',
    cost: 4,
    requires: ['magic_mastery'],
    effect: 'magic_damage_pct',
    value: 1.5,
    x: 16,
    y: 62,
  },
  {
    id: 'spell_fortune_3',
    branch: 'magia',
    name: 'Escrita Astral',
    description: '+0,15% na chance de obter magia.',
    cost: 4,
    requires: ['magic_mastery'],
    effect: 'spell_drop_pct',
    value: 0.15,
    x: 16,
    y: 72,
  },
  {
    id: 'magic_focus_4',
    branch: 'magia',
    name: 'Pulso do Éter',
    description: '+2% de dano mágico.',
    cost: 5,
    requires: ['magic_focus_3'],
    effect: 'magic_damage_pct',
    value: 2,
    x: 8,
    y: 58,
  },
  {
    id: 'spell_fortune_4',
    branch: 'magia',
    name: 'Grimório Vivo',
    description: '+0,2% na chance de obter magia.',
    cost: 5,
    requires: ['spell_fortune_3'],
    effect: 'spell_drop_pct',
    value: 0.2,
    x: 8,
    y: 78,
  },
  {
    id: 'magic_legacy',
    branch: 'magia',
    name: 'Arquimago de Abdoria',
    description: '+2,5% de dano mágico.',
    cost: 6,
    requires: ['magic_focus_4', 'spell_fortune_4'],
    effect: 'magic_damage_pct',
    value: 2.5,
    x: 3,
    y: 68,
  },
  {
    id: 'search_4',
    branch: 'fortuna',
    name: 'Passos do Batedor',
    description: '-350ms na procura.',
    cost: 4,
    requires: ['search_3'],
    effect: 'search_reduction_ms',
    value: 350,
    x: 84,
    y: 57,
  },
  {
    id: 'luck_4',
    branch: 'fortuna',
    name: 'Trevo Ancestral',
    description: '+0,08% de chance de drop.',
    cost: 4,
    requires: ['luck_3'],
    effect: 'drop_chance_pct',
    value: 0.08,
    x: 85,
    y: 76,
  },
  {
    id: 'search_5',
    branch: 'fortuna',
    name: 'Trilha Invisível',
    description: '-400ms na procura.',
    cost: 5,
    requires: ['search_4'],
    effect: 'search_reduction_ms',
    value: 400,
    x: 92,
    y: 59,
  },
  {
    id: 'luck_5',
    branch: 'fortuna',
    name: 'Fortuna Persistente',
    description: '+0,1% de chance de drop.',
    cost: 5,
    requires: ['luck_4'],
    effect: 'drop_chance_pct',
    value: 0.1,
    x: 93,
    y: 81,
  },
  {
    id: 'fortune_legacy',
    branch: 'fortuna',
    name: 'Favor do Destino',
    description: '+0,12% de chance de drop.',
    cost: 6,
    requires: ['search_5', 'luck_5'],
    effect: 'drop_chance_pct',
    value: 0.12,
    x: 97,
    y: 69,
  },
  {
    id: 'vitality_4',
    branch: 'sobrevivencia',
    name: 'Seiva Protetora',
    description: '+3% de vida.',
    cost: 4,
    requires: ['vitality_3'],
    effect: 'hero_hp_pct',
    value: 3,
    x: 40,
    y: 16,
  },
  {
    id: 'regen_4',
    branch: 'sobrevivencia',
    name: 'Retorno Veloz',
    description: '-0,5s derrotado.',
    cost: 4,
    requires: ['regen_3'],
    effect: 'defeat_reduction_ms',
    value: 500,
    x: 64,
    y: 15,
  },
  {
    id: 'vitality_5',
    branch: 'sobrevivencia',
    name: 'Sangue da Montanha',
    description: '+4% de vida.',
    cost: 5,
    requires: ['vitality_4'],
    effect: 'hero_hp_pct',
    value: 4,
    x: 37,
    y: 8,
  },
  {
    id: 'regen_5',
    branch: 'sobrevivencia',
    name: 'Vontade Imortal',
    description: '-0,75s derrotado.',
    cost: 5,
    requires: ['regen_4'],
    effect: 'defeat_reduction_ms',
    value: 750,
    x: 66,
    y: 7,
  },
  {
    id: 'survival_legacy',
    branch: 'sobrevivencia',
    name: 'Coração Ancestral',
    description: '+4% de vida.',
    cost: 6,
    requires: ['vitality_5', 'regen_5'],
    effect: 'hero_hp_pct',
    value: 4,
    x: 51,
    y: 5,
  },
] as const;

const SKILL_BY_ID = new Map(AFK_SKILL_NODES.map((node) => [node.id, node]));

export function getAfkSkillNode(id: string): AfkSkillNodeDefinition | null {
  return SKILL_BY_ID.get(id) ?? null;
}

export function getAfkSkillTotal(
  unlocked: readonly string[] | undefined,
  effect: AfkSkillEffect,
): number {
  const ids = new Set(unlocked ?? []);
  return AFK_SKILL_NODES.reduce(
    (total, node) => total + (ids.has(node.id) && node.effect === effect ? node.value : 0),
    0,
  );
}

export function canUnlockAfkSkill(unlocked: readonly string[], nodeId: string): boolean {
  const node = getAfkSkillNode(nodeId);
  if (!node || unlocked.includes(node.id)) return false;
  return node.requires.every((required) => unlocked.includes(required));
}

export function afkHeroMaxHp(unlocked?: readonly string[]): number {
  return Math.round(250 * (1 + getAfkSkillTotal(unlocked, 'hero_hp_pct') / 100));
}

export function afkDefeatDurationMs(unlocked?: readonly string[]): number {
  return Math.max(6_000, 10_000 - getAfkSkillTotal(unlocked, 'defeat_reduction_ms'));
}

export function afkSearchReductionMs(unlocked?: readonly string[]): number {
  return getAfkSkillTotal(unlocked, 'search_reduction_ms');
}
