import { withCustomParams, withLevelParams } from '../utils/exercise-params.js';
import { prioritySExercises } from './priority-s-exercises.js';

const priorityBase = prioritySExercises.map((e) =>
  withLevelParams({
    ...e,
    modo: e.prioridade === 'isometrico' ? 'tempo' : e.prioridade === 'dinamico' ? 'ambos' : 'reps',
  }),
);

export const additionalExercises = [
  withLevelParams({
    slug: 'heel-touches',
    nome: 'Heel Touches',
    nivel: 1,
    musculo_principal: 'obliquos',
    tempo_recomendado: 30,
    prioridade: 'A',
    descricao: 'Toques alternados nos calcanhares para ativar os oblíquos.',
    media: { gif: 'heel-touches.gif' },
    ativo: true,
  }),
  withLevelParams({
    slug: 'dead-bug',
    nome: 'Dead Bug',
    nivel: 2,
    musculo_principal: 'core',
    tempo_recomendado: 30,
    prioridade: 'A',
    descricao: 'Estabilização do core com movimento contralateral.',
    media: { gif: 'dead-bug.gif' },
    ativo: true,
  }),
  withCustomParams(
    {
      slug: 'hollow-hold',
      nome: 'Hollow Hold',
      nivel: 3,
      musculo_principal: 'core',
      tempo_recomendado: 30,
      prioridade: 'isometrico',
      descricao: 'Isometria em posição oca para core completo.',
      media: { gif: 'hollow-hold.gif' },
      ativo: true,
    },
    { tempo_seg_iniciante: 20, tempo_seg_intermediario: 30, tempo_seg_avancado: 45 },
  ),
  withLevelParams({
    slug: 'scissor-kicks',
    nome: 'Scissor Kicks',
    nivel: 2,
    musculo_principal: 'inferior',
    tempo_recomendado: 30,
    prioridade: 'A',
    descricao: 'Chutes alternados para abdômen inferior.',
    media: { gif: 'scissor-kicks.gif' },
    ativo: true,
  }),
  withLevelParams({
    slug: 'jackknife-sit-up',
    nome: 'Jackknife Sit-Up',
    nivel: 3,
    musculo_principal: 'superior',
    musculos_secundarios: ['inferior'],
    tempo_recomendado: 30,
    prioridade: 'B',
    descricao: 'Flexão completa unindo tronco e pernas.',
    media: { gif: 'jackknife-sit-up.gif' },
    ativo: true,
  }),
  withLevelParams({
    slug: 'windshield-wipers',
    nome: 'Windshield Wipers',
    nivel: 4,
    musculo_principal: 'obliquos',
    tempo_recomendado: 30,
    prioridade: 'B',
    descricao: 'Rotação controlada das pernas para oblíquos avançados.',
    media: { gif: 'windshield-wipers.gif' },
    ativo: true,
  }),
  withCustomParams(
    {
      slug: 'burpee',
      nome: 'Burpee',
      nivel: 3,
      musculo_principal: 'completo',
      tempo_recomendado: 30,
      prioridade: 'dinamico',
      descricao: 'Exercício dinâmico de corpo inteiro.',
      media: { gif: 'burpee.gif' },
      ativo: true,
      modo: 'reps',
    },
    { repeticoes_iniciante: 8, repeticoes_intermediario: 12, repeticoes_avancado: 15 },
  ),
  withCustomParams(
    {
      slug: 'plank-jacks',
      nome: 'Plank Jacks',
      nivel: 2,
      musculo_principal: 'core',
      musculos_secundarios: ['completo'],
      tempo_recomendado: 30,
      prioridade: 'dinamico',
      descricao: 'Prancha com abertura de pernas.',
      media: { gif: 'plank-jacks.gif' },
      ativo: true,
      modo: 'tempo',
    },
    { tempo_seg_iniciante: 20, tempo_seg_intermediario: 30, tempo_seg_avancado: 40 },
  ),
  withCustomParams(
    {
      slug: 'v-hold',
      nome: 'V-Hold',
      nivel: 4,
      musculo_principal: 'core',
      musculos_secundarios: ['inferior'],
      tempo_recomendado: 30,
      prioridade: 'isometrico',
      descricao: 'Isometria em V para core avançado.',
      media: { gif: 'v-hold.gif' },
      ativo: true,
    },
    { tempo_seg_iniciante: 15, tempo_seg_intermediario: 25, tempo_seg_avancado: 40 },
  ),
  withLevelParams({
    slug: 'russian-twist',
    nome: 'Russian Twist',
    nivel: 2,
    musculo_principal: 'obliquos',
    tempo_recomendado: 30,
    prioridade: 'A',
    descricao: 'Rotação de tronco sentado para oblíquos.',
    media: { gif: 'russian-twist.gif' },
    ativo: true,
  }),
  withLevelParams({
    slug: 'flutter-kicks',
    nome: 'Flutter Kicks',
    nivel: 2,
    musculo_principal: 'inferior',
    tempo_recomendado: 30,
    prioridade: 'A',
    descricao: 'Chutes alternados rápidos para abdômen inferior.',
    media: { gif: 'flutter-kicks.gif' },
    ativo: true,
  }),
  withLevelParams({
    slug: 'toe-touches',
    nome: 'Toe Touches',
    nivel: 1,
    musculo_principal: 'superior',
    tempo_recomendado: 30,
    prioridade: 'A',
    descricao: 'Flexão de tronco tocando os pés.',
    media: { gif: 'toe-touches.gif' },
    ativo: true,
  }),
  withLevelParams({
    slug: 'sit-up',
    nome: 'Sit-Up',
    nivel: 1,
    musculo_principal: 'superior',
    tempo_recomendado: 30,
    prioridade: 'A',
    descricao: 'Flexão completa de tronco clássica.',
    media: { gif: 'sit-up.gif' },
    ativo: true,
  }),
  withCustomParams(
    {
      slug: 'side-plank',
      nome: 'Side Plank',
      nivel: 2,
      musculo_principal: 'obliquos',
      tempo_recomendado: 30,
      prioridade: 'isometrico',
      descricao: 'Prancha lateral para oblíquos e estabilidade.',
      media: { gif: 'side-plank.gif' },
      ativo: true,
    },
    { tempo_seg_iniciante: 20, tempo_seg_intermediario: 30, tempo_seg_avancado: 45 },
  ),
  withCustomParams(
    {
      slug: 'bear-crawl',
      nome: 'Bear Crawl',
      nivel: 3,
      musculo_principal: 'completo',
      tempo_recomendado: 30,
      prioridade: 'dinamico',
      descricao: 'Deslocamento quadrúpede dinâmico.',
      media: { gif: 'bear-crawl.gif' },
      ativo: true,
      modo: 'tempo',
    },
    { tempo_seg_iniciante: 20, tempo_seg_intermediario: 30, tempo_seg_avancado: 40 },
  ),
  withLevelParams({
    slug: 'spiderman-plank',
    nome: 'Spiderman Plank',
    nivel: 3,
    musculo_principal: 'obliquos',
    musculos_secundarios: ['core'],
    tempo_recomendado: 30,
    prioridade: 'B',
    descricao: 'Prancha com joelho ao cotovelo alternado.',
    media: { gif: 'spiderman-plank.gif' },
    ativo: true,
  }),
  withCustomParams(
    {
      slug: 'hanging-knee-raise',
      nome: 'Hanging Knee Raise',
      nivel: 4,
      musculo_principal: 'inferior',
      tempo_recomendado: 30,
      prioridade: 'B',
      descricao: 'Elevação de joelhos na barra fixa.',
      media: { gif: 'hanging-knee-raise.gif' },
      ativo: true,
    },
    { repeticoes_iniciante: 8, repeticoes_intermediario: 12, repeticoes_avancado: 15 },
  ),
  withCustomParams(
    {
      slug: 'stability-ball-crunch',
      nome: 'Stability Ball Crunch',
      nivel: 2,
      musculo_principal: 'superior',
      tempo_recomendado: 30,
      prioridade: 'B',
      descricao: 'Crunch sobre bola suíça com maior amplitude.',
      media: { gif: 'stability-ball-crunch.gif' },
      ativo: true,
    },
    { repeticoes_iniciante: 10, repeticoes_intermediario: 15, repeticoes_avancado: 20 },
  ),
  withLevelParams({
    slug: 'thread-the-needle',
    nome: 'Thread the Needle',
    nivel: 2,
    musculo_principal: 'obliquos',
    musculos_secundarios: ['core'],
    tempo_recomendado: 30,
    prioridade: 'B',
    descricao: 'Rotação de tronco em prancha para mobilidade e core.',
    media: { gif: 'thread-the-needle.gif' },
    ativo: true,
  }),
  withCustomParams(
    {
      slug: 'dragon-flag',
      nome: 'Dragon Flag',
      nivel: 4,
      musculo_principal: 'core',
      musculos_secundarios: ['superior', 'inferior'],
      tempo_recomendado: 30,
      prioridade: 'B',
      descricao: 'Movimento avançado de controle corporal.',
      media: { gif: 'dragon-flag.gif' },
      ativo: true,
    },
    { repeticoes_iniciante: 3, repeticoes_intermediario: 5, repeticoes_avancado: 8 },
  ),
  withCustomParams(
    {
      slug: 'l-sit',
      nome: 'L-Sit',
      nivel: 4,
      musculo_principal: 'core',
      musculos_secundarios: ['inferior'],
      tempo_recomendado: 30,
      prioridade: 'isometrico',
      descricao: 'Isometria em L para core e flexores.',
      media: { gif: 'l-sit.gif' },
      ativo: true,
    },
    { tempo_seg_iniciante: 10, tempo_seg_intermediario: 20, tempo_seg_avancado: 30 },
  ),
  withCustomParams(
    {
      slug: 'ab-wheel',
      nome: 'Ab Wheel Rollout',
      nivel: 4,
      musculo_principal: 'core',
      musculos_secundarios: ['superior'],
      tempo_recomendado: 30,
      prioridade: 'B',
      descricao: 'Rolinho abdominal para core avançado.',
      media: { gif: 'ab-wheel.gif' },
      ativo: true,
    },
    { repeticoes_iniciante: 5, repeticoes_intermediario: 8, repeticoes_avancado: 12 },
  ),
  withCustomParams(
    {
      slug: 'copenhagen-plank',
      nome: 'Copenhagen Plank',
      nivel: 4,
      musculo_principal: 'obliquos',
      tempo_recomendado: 30,
      prioridade: 'isometrico',
      descricao: 'Prancha lateral avançada com perna elevada.',
      media: { gif: 'copenhagen-plank.gif' },
      ativo: true,
    },
    { tempo_seg_iniciante: 15, tempo_seg_intermediario: 25, tempo_seg_avancado: 35 },
  ),
  {
    slug: 'push-up',
    nome: 'Push-Up',
    nome_pt: 'Flexão',
    nivel: 2,
    musculo_principal: 'superior',
    musculos_secundarios: ['core'],
    tempo_recomendado: 30,
    prioridade: 'A',
    descricao: 'Flexão clássica de braços com estabilização do core.',
    media: { gif: 'push-up.gif' },
    ativo: true,
  },
  {
    slug: 'incline-push-up',
    nome: 'Incline Push-Up',
    nome_pt: 'Flexão inclinada',
    nivel: 1,
    musculo_principal: 'superior',
    musculos_secundarios: ['core'],
    tempo_recomendado: 30,
    prioridade: 'A',
    descricao: 'Flexão com mãos elevadas — ideal para iniciantes.',
    media: { gif: 'incline-push-up.gif' },
    ativo: true,
  },
  {
    slug: 'decline-push-up',
    nome: 'Decline Push-Up',
    nome_pt: 'Flexão declinada',
    nivel: 3,
    musculo_principal: 'superior',
    musculos_secundarios: ['core'],
    tempo_recomendado: 30,
    prioridade: 'B',
    descricao: 'Flexão com pés elevados — maior intensidade no core e peito.',
    media: { gif: 'decline-push-up.gif' },
    ativo: true,
  },
];

export const allExercises = [...priorityBase, ...additionalExercises];
